apiVersion: integration/v1
kind: Step
name: cat-team-github-metrics
version: 1
summary: A relay step to collect metrics from GitHub and publish them to BigQuery.

description: |
  This step will invoke the metric collector app which will scrape the provided repository
  for metrics and upload them to Big Query.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: puppetlabs/cat-team-github-metrics

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    properties:
      github_token:
        type: string
        description: A GitHub PAT token.
        writeOnly: true
      big_query_project_id:
        type: string
        description: The GCP project id that contains the Big Query instance.
        writeOnly: true
      repo_owner:
        type: string
        description: The owner of the GitHub repository (e.g. puppetlabs)
      repo_name:
        type: string
        description: The name of the GitHub repository (e.g. puppetlabs-docker)
    required:
      - github_token
      - big_query_project_id
      - repo_owner
      - repo_name
